name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and push Docker image
      run: |
        # Generate timestamp once for consistency
        TIMESTAMP=$(date +%s)
        
        # Build and tag in one step
        docker build . \
          --file Dockerfile \
          --tag ghcr.io/clapeyre/pico-wallet-server:$TIMESTAMP
        
        # Push using the same explicit tag
        docker push ghcr.io/clapeyre/pico-wallet-server:$TIMESTAMP
